### ISSUE TITLE
Dev environment setup guide

### ISSUE THREAD

**Issue by rolodato** [topisani/TOP-1#2]
I'd like to start diving into this project but with my limited time and knowledge of C++, it's complicated. I'm sure it would help many other potential contributors if there was a quick setup guide/Docker container/VM image/etc to get started hacking on this. Creating this issue mostly so I get a notification if it's ever done :)

Thanks and best of luck with this project!

**Comment by teesloane** [comment]
I'd like to second this! I quite like writing documentation but I am unfamiliar with C++. If I can get enough guidance to get a stack running on my own machine then I will happily write a guide / work on whatever needs to be documented.

**Comment by topisani** [comment]
come on over to https://discord.gg/4cV9Ucz if youre not there already - we are already discussing this, and id love to help someone write this guide or setup a docker container - @teesloane if you want to help and like writing documentation, id love it if you could help writing some more generally - a lot of it is needed, and i prefer coding to writing :wink: Come to the chat and we'll talk about it!

**Comment by teesloane** [comment]
Sounds good @topisani . I will periodically step into the discord server and see what I can do.
